### ISSUE TITLE
Missing %apps-list.reb

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/rebol-server#1]
First issue!  :-)

After building the rebol-server locally and packaging it, I install it.

The R3 CONSOLE button works.  However, when I go to the FILES and click on "apps" I get a page that says:

> `** Access Error: cannot open: %/data/user/0/giuliolunati.rebolserver/files/apps/apps-list.reb`

*(Was seeking the behavior from [the conference video](https://drive.google.com/drive/folders/1xI7kSbZfZV4V3L74fREoYOTAeTO6L2i_), where it says "Installed Apps", "Available Apps", "Custom Install...")*

It would appear that clicking on "apps" is running %apps/index.reb, which [explicitly looks for this file](https://github.com/metaeducation/rebol-server/blob/08f75658c5a4a472007d32138501aec7f177817e/assets-src/apps/index.reb#L32).  But the file is not in the [%assets-src/apps/](https://github.com/metaeducation/rebol-server/tree/master/assets-src/apps) directory.

**Comment by giuliolunati** [comment]
[Fixed](https://github.com/metaeducation/rebol-server/commit/36ff43955497547484a417cfb6b10407de64e5cd), I hope. Thank you for report!

**Comment by giuliolunati** [comment]
No idea... what about your system?

A side note: after reinstalling app w/out disinstalling before, better to click "Reinstall System"
