### ISSUE TITLE
"This app was built for an older version of Android"

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/rebol-server#3]
When I finish the .APK build process and run the Rebol Server, it installs...but the first time it launches it says:

> This app was built for an older version of Android and may not work properly.  Try checking for updates, or contact the developer.

The phone is a moto g(6) play.  It says it has Android version 9.  The Build number is PPP29.118-17-1.

It seems to work okay, but I don't know anything about Android versioning... :-/  Is there any way we can use some lowest common denominator of features and declare "it's fine for version 9"?

**Comment by giuliolunati** [comment]
Sure! in AndroidManifest.xml set targetSdkVersion=28

See https://developer.android.com/guide/topics/manifest/uses-sdk-element

**Comment by giuliolunati** [comment]
"Hmmm...I guess there is no way to build one version of the .APK that can be loaded on both version 9 and before without this warning? It seems like the Google Play store makes multiple .APK and then gives you the right one"

targetSdkVersion=nn works well for ALL mm <= nn, so np to set nn=28

**Comment by giuliolunati** [comment]
just tried it, works fine with Android 7.0

**Comment by giuliolunati** [comment]
Fixed in 883c6c9

**Comment by giuliolunati** [comment]
I hope solved in f6b29fe
