### ISSUE TITLE
Enable Travis CI Building of APK

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/rebol-server#4]
I've started a `.travis.yml` file, based on the code from Ren-C's Travis:

https://github.com/metaeducation/rebol-server/commit/d75d161b2ed370e458e1bfb37cf354f004703529

It doesn't work.  :-/  But @giuliolunati, since you have probably built on Linux before then maybe you would know some things to improve.

Right now this starting file is failing saying it can't find the necessary packages, presumably because they come from another repository vs. the Debian standard ones?

I'm not sure where to upload the files...what to call them...whether to use the commit ID of the embedded Rebol or of the rebol-server project.  Basically this is me just trying to get it turned on so we can figure that out!

**Comment by giuliolunati** [comment]
commit 439a4907 reaches the SIGNING step, but then hangs here, dunno way :-/

Another issue is having the signing key publicy available

**Comment by giuliolunati** [comment]
Starting from e175a7f1, it builds and deploys.
