### ISSUE TITLE
Pare down inclusion of rebol-httpd to just httpd.reb

### ISSUE THREAD

**Issue by hostilefork** [metaeducation/rebol-server#7]
The httpd.reb is now in its own submodule:

https://github.com/metaeducation/rebol-httpd

As a first cut of including it in the APK, it just zips the whole directory.  But that means including the README.md, LICENSE, tests, etc.

The zip method should be updated in some way to get only the relevant files.  But since it's currently a bash script that does a "zip *" that will have to be rethought.

Is it time to start taking a r3 executable for granted and lay out some specifications of what files are needed as Rebol, and to use the Rebol zipping facility?

**Comment by giuliolunati** [comment]
Solved in 8006b75
